config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :employees

  root 'organizations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_employee!

	private

	def after_sign_in_path_for(resource)
		case resource
		  when Employee then root_path 
		  when User then admin_dashboard_path
		  end
    end

	def after_sign_out_path_for(employee)
    new_employee_session_path(employee)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[ show edit update destroy ]

  # GET /organizations or /organizations.json
  def index
    @organizations = Organization.page params[:page]
  end

  # GET /organizations/1 or /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations or /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:title, :phone, :email, :website, :description, :status)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include SettingsHelper

  def nav_bar(&block)
    content_tag(:ul, class: 'navbar-nav', &block)
  end

  def nav_link(path, &block)
    options = current_page?(path) ? { class: 'nav-item active' } : { class: 'nav-item' }
    content_tag(:li, options) do
      link_to path, class: 'nav-link', &block
    end
  end

  def settings_nav_link(&block)
    options = current_page?(edit_organization_path(@organization)) || roles_page? ? { class: 'nav-item active' } : { class: 'nav-item' }
    content_tag(:li, options) do
      link_to edit_organization_path(@organization), class: 'nav-link', &block
    end
  end

  def roles_page?
    controller = 'roles'
    actions = %w[index new edit]
    actions.any? { |action| params[:controller] == controller && params[:action] == action }
  end

  def organizations
    @organizations ||= Organization.all #current_user.spaces.order(:name).filter(&:active?)
  end

  def abbrev_name(name)
    name.blank? ? '?' : name.split(' ').map(&:first).join('.')
  end

  def demo_mode?
    ENV['DEMO_MODE'] == 'true'
  end


  def employee_name(employee)
    "#{employee.first_name} #{employee.last_name}"
  end  

  def employee_status(employee)
    0  
  end  

  def employee_admin?(employee)
    true
  end  
  
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
	def multi_organization_mode?
		Organization.many?
	end	
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
  def has?(permission)
    @role.send("can_#{permission}?")
  end
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
  def login_layout
    case ['ILLUSTRATION', 'COVER'][0]
    when 'ILLUSTRATION'
      'body/login_illustration'
    when 'COVER'
      'body/login_cover'
    else
      'body/login'
    end
  end

  def interface_layout
    case ['VERTICAL', 'VERTICAL-TRANSPARENT', 'OVERLAP', 'CONDENSED'][0]
    when 'VERTICAL'
      'body/vertical'
    when 'VERTICAL-TRANSPARENT'
      'body/vertical_transparent'
    when 'OVERLAP'
      'body/overlap'
    when 'CONDENSED'
      'body/condensed'
    else
      'body/horizontal'
    end
  end

  def interface_mode
    case ['DARK', 'LIGHT'][0]
    when 'DARK'
      'dark'
    else
      'light'
    end
  end
end

app/views/body/_condensed.html.erb
<body class="<%= interface_mode %>">
  <div class="page">
    <!-- Navbar -->
    <header class="navbar navbar-expand-md navbar-light d-print-none">
      <div class="container-xl">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
          <a href="/">
            <%#= image_tag "logo.svg", width: "110", height: "32", alt: "Portal", class: "navbar-brand-image" %>
          </a>
        </h1>
        <div class="navbar-nav flex-row order-md-last">
          <%= render 'common/profile_dropdown' %>
        </div>
        <div class="collapse navbar-collapse" id="navbar-menu">
          <%= render 'common/nav_items' %>
        </div>
      </div>
    </header>
    <div class="page-wrapper">
      <!-- Page header -->
      <div class="page-header d-print-none">
        <div class="container-xl">
          <div class="row g-2 align-items-center">
            <%= render 'common/section_title' %>
            <!-- Page title actions -->
            <div class="col-auto ms-auto d-print-none">
              <%= render 'common/space_selector' %>
            </div>
          </div>
        </div>
      </div>
      <!-- Page body -->
      <div class="page-body">
        <div class="container-xl">
          <% if notice %>
            <p class="alert alert-success alert-dismissible"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger alert-dismissible"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <%= render 'common/footer' %>
    </div>
  </div>
</body>

app/views/body/_horizontal.html.erb
<body class="d-flex flex-column min-vh-100"  data-bs-theme="<%= interface_mode %>">
  <header class="navbar navbar-expand-md navbar-light d-print-none">
    <div class="container-xl">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
        <a href="/">
          <%#= image_tag "logo.svg", width: "110", height: "32", alt: "Portal", class: "navbar-brand-image" %>
        </a>
      </h1>
      <div class="navbar-nav flex-row order-md-last">
        <%= render 'common/profile_dropdown' %>
      </div>
    </div>
  </header>
  <div class="wrapper flex-grow-1">
    <div class="navbar-expand-md">
      <div class="collapse navbar-collapse" id="navbar-menu">
        <div class="navbar navbar-light">
          <div class="container-xl">
            <%= render 'common/nav_items' %>
            <div class="my-md-0 flex-grow-1 flex-md-grow-0 order-first order-md-last">
              <%= render 'common/space_selector' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="page-wrapper">
      <div class="container-xl">
        <!-- Page title -->
        <div class="page-header d-print-none">
          <div class="row align-items-center">
            <%= render 'common/section_title' %>
          </div>
        </div>
      </div>
      <div class="page-body">
        <div class="container-xl">
          <% if notice %>
            <p class="alert alert-success alert-dismissible"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger alert-dismissible"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'common/footer' %>
</body>

app/views/body/_login.html.erb
<body  class="d-flex flex-column <%= interface_mode %>">
  <div class="page page-center">
    <div class="container-tight py-4">
      <% if notice %>
        <p class="alert alert-success alert-dismissible"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger alert-dismissible"><%= alert %></p>
      <% end %>
      <div class="text-center mb-4">
        <a href="/" class="navbar-brand navbar-brand-autodark"><%#= image_tag "logo.svg", height: '36' %></a>
      </div>
      <%= yield %>
    </div>
  </div>
</body>

app/views/body/_login_cover.html.erb
<body  class="d-flex flex-column <%= interface_mode %>">
  <div class="row g-0 flex-fill">
    <div class="col-12 col-lg-6 col-xl-8 d-none d-lg-block">
      <!-- Photo -->
      <div class="bg-cover h-100 min-vh-100" style="background-image: url(/finances-us-dollars-and-bitcoins-currency-money-2.jpg)"></div>
    </div>
    <div class="col-12 col-lg-6 col-xl-4 border-top-wide border-primary d-flex flex-column justify-content-center">
      <div class="container container-tight my-5 px-lg-5">
        <% if notice %>
          <p class="alert alert-success alert-dismissible"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger alert-dismissible"><%= alert %></p>
        <% end %>
        <div class="text-center mb-4">
          <a href="/" class="navbar-brand navbar-brand-autodark"><%#= image_tag "logo.svg", height: '36' %></a>
        </div>
        <%= yield %>
      </div>
    </div>
  </div>
</body>

app/views/body/_login_illustration.html.erb
<body  class="d-flex flex-column <%= interface_mode %>">
  <div class="page page-center">
    <div class="container container-normal py-4">
      <div class="row align-items-center g-4">
        <div class="col-lg">
          <div class="container-tight">
            <% if notice %>
              <p class="alert alert-success alert-dismissible"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger alert-dismissible"><%= alert %></p>
            <% end %>
            <div class="text-center mb-4">
              <a href="/" class="navbar-brand navbar-brand-autodark"><%#= image_tag "logo.svg", height: '36' %></a>
            </div>
            <%= yield %>
          </div>
        </div>
        <div class="col-lg d-none d-lg-block">
          <img src="/undraw_secure_login_pdn4.svg" height="300" class="d-block mx-auto" alt="">
        </div>
      </div>
    </div>
  </div>
</body>

app/views/body/_overlap.html.erb
<body class="<%= interface_mode %>">
  <div class="page">
    <header class="navbar navbar-expand-md navbar-dark navbar-overlap d-print-none">
      <div class="container-xl">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
          <a href="/">
            <%#= image_tag "logo-white.svg", width: "110", height: "32", alt: "Portal", class: "navbar-brand-image" %>
          </a>
        </h1>
        <div class="navbar-nav flex-row order-md-last">
          <div class="d-none d-md-flex">
          </div>
          <%= render 'common/profile_dropdown' %>
        </div>
        <div class="collapse navbar-collapse" id="navbar-menu">
          <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
            <%= render 'common/nav_items' %>
          </div>
        </div>
      </div>
    </header>
    <div class="page-wrapper">
      <div class="container-xl">
        <!-- Page title -->
        <div class="page-header d-print-none ">
          <div class="row g-2 align-items-center">
            <!-- Page title actions -->
            <div class="navbar-expand-md">
              <div class="navbar">
                <div class="text-white">
                  <%= render 'common/section_title' %>
                </div>
                <div class="col-12 col-md-auto ms-auto d-print-none">
                  <%= render 'common/space_selector' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="page-body">
        <div class="container-xl">
          <% if notice %>
            <p class="alert alert-success alert-dismissible"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger alert-dismissible"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <%= render 'common/footer' %>
    </div>
  </div>
</body>

app/views/body/_vertical.html.erb
<body class="<%= interface_mode %>">
  <div class="page">
    <aside class="navbar navbar-vertical navbar-expand-lg navbar-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark">
          <a href="/">
            <%#= image_tag "logo.svg", width: "110", height: "32", alt: "Portal", class: "navbar-brand-image" %>
          </a>
        </h1>
        <div class="navbar-nav flex-row d-lg-none">
          <%= render 'common/profile_dropdown' %>
        </div>
        <!-- Navbar -->
        <div class="collapse navbar-collapse" id="navbar-menu">
          <%= render 'common/nav_items' %>
          <div class="my-md-0 flex-grow-1 flex-md-grow-0 order-first order-md-first">
            <%= render 'common/space_selector' %>
          </div>
        </div>
      </div>
    </aside>
    <div class="page-wrapper">
      <div class="container-xl">
        <div class="flex-row mb-4">
          <!-- Page title -->
          <div class="page-header d-print-none">
            <div class="row align-items-center">
              <%= render 'common/section_title' %>
              <div class="d-none d-lg-flex col flex-row-reverse">
                <%= render 'common/profile_dropdown' %>
              </div>
            </div>
          </div>
        </div>
        <% if notice %>
          <p class="alert alert-success alert-dismissible"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger alert-dismissible"><%= alert %></p>
        <% end %>
      </div>
      <div class="page-body">
        <div class="container-xl">
          <%= yield %>
        </div>
      </div>
      <%= render 'common/footer' %>
    </div>
  </div>
</body>

app/views/body/_vertical_transparent.html.erb
<body class="<%= interface_mode %>">
  <div class="page">
    <aside class="navbar navbar-vertical navbar-expand-lg navbar-transparent">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark">
          <a href="/">
            <%#= image_tag "logo.svg", width: "110", height: "32", alt: "Portal", class: "navbar-brand-image" %>
          </a>
        </h1>
        <div class="navbar-nav flex-row d-lg-none">
          <%= render 'common/profile_dropdown' %>
        </div>
        <!-- Navbar -->
        <div class="collapse navbar-collapse" id="navbar-menu">
          <%= render 'common/nav_items' %>
          <div class="my-md-0 flex-grow-1 flex-md-grow-0 order-first order-md-first">
            <%= render 'common/space_selector' %>
          </div>
        </div>
      </div>
    </aside>
    <div class="page-wrapper">
      <div class="container-xl">
        <div class="flex-row mb-4">
          <!-- Page title -->
          <div class="page-header d-print-none">
            <div class="row align-items-center">
              <%= render 'common/section_title' %>
              <div class="d-none d-lg-flex col flex-row-reverse">
                <%= render 'common/profile_dropdown' %>
              </div>
            </div>
          </div>
        </div>
        <% if notice %>
          <p class="alert alert-success alert-dismissible"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger alert-dismissible"><%= alert %></p>
        <% end %>
      </div>
      <div class="page-body">
        <div class="container-xl">
          <%= yield %>
        </div>
      </div>
      <%= render 'common/footer' %>
    </div>
  </div>
</body>

app/views/common/_footer.html.erb
<footer class="footer footer-transparent d-print-none mt-auto">
  <div class="container-xl">
    <div class="row text-center align-items-center flex-row-reverse">
      <div class="col-lg-auto ms-lg-auto">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            <a href="http//www.codiatic.com" class="link-secondary">
            http//www.codiatic.com
            </a>
          </li>
        </ul>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            Copyright &copy; 2023
            <a href="." class="link-secondary">Codiatic Technologies</a>.
            All rights reserved.
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/common/_nav_items.html.erb
<%= nav_bar do %>
  <% if @space&.id.present? %>
    <%= nav_link @space do %>
      <span class="nav-link-icon d-md-none d-lg-inline-block">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home" width="40" height="40" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <polyline points="5 12 3 12 12 3 21 12 19 12"></polyline>
          <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
          <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
        </svg>
      </span>
      <span class="nav-link-title">
        Home
      </span>
    <% end %>
    <%= nav_link space_users_path(@space) do %>
      <span class="nav-link-icon d-md-none d-lg-inline-block">
        <!-- Download SVG icon from http://tabler-icons.io/i/users -->
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-users" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <circle cx="9" cy="7" r="4"></circle>
          <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
          <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
          <path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path>
        </svg>
      </span>
      <span class="nav-link-title">
        Users
      </span>
    <% end %>
    <%= settings_nav_link do %>
      <span class="nav-link-icon d-md-none d-lg-inline-block">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-settings" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <desc>Download more icon variants from https://tabler-icons.io/i/settings</desc>
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z"></path>
          <circle cx="12" cy="12" r="3"></circle>
        </svg>
      </span>
      <span class="nav-link-title">
        Settings
      </span>
    <% end %>
    <% if demo_mode? %>
      <%= nav_link edit_setup_path do %>
        <span class="nav-link-icon d-md-none d-lg-inline-block">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-adjustments" width="40" height="40" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <circle cx="6" cy="10" r="2"></circle>
            <line x1="6" y1="4" x2="6" y2="8"></line>
            <line x1="6" y1="12" x2="6" y2="20"></line>
            <circle cx="12" cy="16" r="2"></circle>
            <line x1="12" y1="4" x2="12" y2="14"></line>
            <line x1="12" y1="18" x2="12" y2="20"></line>
            <circle cx="18" cy="7" r="2"></circle>
            <line x1="18" y1="4" x2="18" y2="5"></line>
            <line x1="18" y1="9" x2="18" y2="20"></line>
          </svg>
        </span>
        <span class="nav-link-title">
          Demo Setup
        </span>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/common/_profile_dropdown.html.erb
<div class="nav-item dropdown">
  <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
    <span  class="avatar">
      <!-- Download SVG icon from http://tabler-icons.io/i/dashboard -->
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle"
      width="48" height="48" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
      stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <circle cx="12" cy="12" r="9"></circle><circle cx="12" cy="10" r="3"></circle>
          <path d="M6.168 18.849a4 4 0 0 1 3.832-2.849h4a4 4 0 0 1 3.834 2.855">
        </path>
      </svg>
    </span>
    <div class="d-none d-xl-block ps-2">
      <div><%= employee_name(current_employee) %></div>
      <div class="mt-1 small text-muted"><%= employee_status(current_employee) %></div>
    </div>
  </a>
  <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
    <%= link_to 'Profile', edit_employee_registration_path(current_employee),  class: 'dropdown-item' %>
    <%= link_to 'Change password', edit_employee_password_path, class: 'dropdown-item' %>
    <% if multi_organization_mode? %>
      <%= link_to 'Spaces', organizations_path, class: 'dropdown-item' %>
    <% end %>
    <% if employee_admin?(current_employee) %>
      <div class="dropdown-divider"></div>
      <%= link_to 'Setup', '#', class: 'dropdown-item', target: '_blank' %>
      <%= link_to 'Admin', 'active_admin_path', class: 'dropdown-item', target: '_blank' %>
      <%= link_to 'Sidekiq', '#', class: 'dropdown-item', target: '_blank' %>
    <% end %>
    <div class="dropdown-divider"></div>
    <%= button_to "Logout", destroy_employee_session_path, data: { turbo: false }, class: 'dropdown-item', method: :delete  %>
  </div>
</div>

app/views/organizations/index.html.erb
<% content_for :page_pretitle do %>
Organizations
<% end %>
<% content_for :page_title do %>
<% @current_employee&.name || 'Index' %>
<% end %>
<div class="row row-cards">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Organizations</h3>
        <div class="card-actions">
          <%= link_to new_organization_path, class: "btn btn-primary" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
              stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <line x1="12" y1="5" x2="12" y2="19" />
            <line x1="5" y1="12" x2="19" y2="12" />
          </svg>
          New organization
          <% end %>
        </div>
      </div>
      <div class="table-responsive">
        
        <table class="table table-vcenter table-mobile-md card-table">
          <thead>
            
              <th>Title</th>
            
              <th>Phone</th>
            
              <th>Email</th>
            
              <th>Website</th>
            
              <th>Description</th>
            
              <th>Status</th>
            
            <th class="w-1"></th>
          </thead>
          <tbody>
            <% @organizations.each do |organization| %>
            <tr>
              
                <td class="text-muted" data-label="Title">
                  <%= organization.title %>
                </td>
              
                <td class="text-muted" data-label="Phone">
                  <%= organization.phone %>
                </td>
              
                <td class="text-muted" data-label="Email">
                  <%= organization.email %>
                </td>
              
                <td class="text-muted" data-label="Website">
                  <%= organization.website %>
                </td>
              
                <td class="text-muted" data-label="Description">
                  <%= organization.description %>
                </td>
              
                <td class="text-muted" data-label="Status">
                  <%= organization.status %>
                </td>
              
              <td>
                <div class="btn-list flex-nowrap">
                  <%= link_to "Edit", edit_organization_path(organization), class: "btn" %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex align-items-center">
          <p class="m-0 text-muted"><%= page_entries_info @organizations%></p>
          <%= paginate @organizations %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="card border">
  <div class="card-body">
    <div>
      <%= render @organization %>
    </div>
    <div>
      <%= link_to "Back to organizations", organizations_path, class: "btn" %>
    </div>
  </div>
</div>